###Array Basics

In [2]:
import numpy as np
a = np.array([5, 5, 5])
a

array([5, 5, 5])

In [3]:
type(a)

numpy.ndarray

In [5]:
# List of lists
b = np.array([[5, 5, 5], [5, 5, 5], [5, 5, 5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
type(b)

numpy.ndarray

In [7]:
len(b)

3

In [8]:
a[0]

5

In [9]:
a[0: ]

array([5, 5, 5])

In [10]:
type(b)

numpy.ndarray

In [11]:
b[0: ]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [14]:
d = np.ones(3)
d

array([1., 1., 1.])

In [15]:
e = np.empty(3)
e

array([1., 1., 1.])

In [17]:
f = np.arange(7)
f

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
g = np.arange(2, 20)
g

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
h = np.arange(2, 20, 2)
h

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
i = np.linspace(0, 10, num=5)
i

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
j = np.ones(5, dtype=np.int8)
j

array([1, 1, 1, 1, 1], dtype=int8)

In [23]:
k = np.ones(5, dtype=np.float64)
k

array([1., 1., 1., 1., 1.])

In [27]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])