# numpy practice session

In [3]:
import numpy as np


# creating an aray using numpy

In [4]:
#1D array
food = np.array(['Pakora', 'Samosa', 'Raita'])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [5]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [8]:
price[2]

5

In [9]:
food[1]

'Samosa'

In [11]:
price.mean()

5.0

In [8]:
# zeroes
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [11]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [15]:
# specific range with interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# table of 5
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [23]:
# array with specific line space
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [27]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#Array functions

In [29]:
a = np.array([10, 12, 15, 2, 4, 6, 100, 320, 0.5, 10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [30]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [31]:
b = np.array([10.2, 3.4, 53, 44])
b

array([10.2,  3.4, 53. , 44. ])

In [36]:
c = np.concatenate((a, b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53. ,  44. ])

In [37]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  44. ,  53. , 100. , 320. ])

# 2-D arrays

In [45]:
a = np.array([[1, 2,], [5, 4]])
a

array([[1, 2],
       [5, 4]])

In [46]:
b = np.array([[6, 7], [8, 9]])
b

array([[6, 7],
       [8, 9]])

In [53]:
c = np.concatenate((a, b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [51]:
c = np.concatenate((a, b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [55]:
b = np.array([[5, 6, 7],
             [8, 9, 10],
             [10, 11, 12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [56]:
b.ndim

2

In [58]:
b.size

9

In [59]:
b.shape

(3, 3)

In [67]:
b = np.arange(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
c = b.reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
np.reshape(b, newshape=(1, 9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [74]:
# convert 1d into 2d
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
a.shape

(7,)

In [78]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7]])

In [79]:
b.shape

(1, 7)

In [81]:
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [82]:
c*6

array([[ 6],
       [12],
       [18],
       [24],
       [30],
       [36],
       [42]])

In [83]:
c.sum()

28

In [84]:
a.mean()

4.0